FROM ghcr.io/cirruslabs/flutter:3.10.0-1.1.pre

RUN apt-get update -y && apt-get upgrade -y

RUN flutter doctor

RUN mkdir /app/
COPY . /app/
WORKDIR /app/

CMD flutter test --coverage --coverage-path=coverage/lcov.info