name: Continous Deployment

on:
  workflow_dispatch:
  schedule:
    - cron: '0 8 * * 1'

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            rm -rf ${{ secrets.GIT_REPO_PATH }}
            git clone ${{ secrets.GIT_REPO_URL }} ${{ secrets.GIT_REPO_PATH }}
            cd ${{ secrets.GIT_REPO_PATH }}
            git checkout ${{ secrets.GIT_BRANCH }}
            git pull origin ${{ secrets.GIT_BRANCH }}
            flutter pub get
            flutter build web --release
            python3 -m http.server 8080 &
        # Add your deploy commands here
        # Prefer using scripts, place them in the scripts folder and call them here

  documentation:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update -y && sudo apt-get upgrade -y
        # Add other dependencies here if needed
        # Prefer using scripts, place them in the scripts folder and call them here

      - name: Build documentation
        run: |
          echo "Building documentation"
        # Add your build commands here
        # Prefer using scripts, place them in the scripts folder and call them here

      - name: Deploy documentation
        run: |
          echo "Deploying documentation"
        # Add your deploy commands here
        # Prefer using scripts, place them in the scripts folder and call them here
