name: Continous Integration

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '* 8 * * *'
  workflow_dispatch:

jobs:
  tests:
    #needs: build
    runs-on: ubuntu-22.04
    container:
      image: ghcr.io/cirruslabs/flutter:3.10.0-1.1.pre
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          echo "Installing dependencies"
        # Add other dependencies here if needed
        # Prefer using scripts, place them in the scripts folder and call them here

      - name: Run tests
        run: |
          echo "Running tests"
          flutter pub get
          flutter test --coverage --coverage-path=coverage/lcov.info
        # Run specific tests here
        # Prefer using scripts, place them in the scripts folder and call them here

      - name: Create ECS documentation artifact
        uses: actions/upload-artifact@v3
        with:
          name: coverage
          path: ./coverage

      - name: Upload ECS documentation
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: ./coverage
          target-folder: docs/coverage
          branch: gh-pages

  linter:
    runs-on: ubuntu-22.04
    container:
      image: ghcr.io/cirruslabs/flutter:3.10.0-1.1.pre
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          echo "Installing dependencies"
        # Add other dependencies here if needed
        # Prefer using scripts, place them in the scripts folder and call them here

      - name: Run linter
        run: |
          echo "Running linter"
          flutter pub get
          dart analyze .
        # Run specific linter here
        # Prefer using scripts, place them in the scripts folder and call them here

  documentation:
    needs: linter
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update -y && sudo apt-get upgrade -y
        # Add other dependencies here if needed
        # Prefer using scripts, place them in the scripts folder and call them here

      - name: Check documentation
        run: |
          echo "Checking documentation"
        # Run specific documentation checker here
        # Prefer using scripts, place them in the scripts folder and call them here

  build:
    needs: linter
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update -y && sudo apt-get upgrade -y
        # Add other dependencies here if needed
        # Prefer using scripts, place them in the scripts folder and call them here

      - name: Build
        run: |
          echo "Building"
          ${{ github.workspace }}/.github/workflows/scripts/build.sh mobile web
        # Run specific build command here
        # Prefer using scripts, place them in the scripts folder and call them here
